# Generated by Django 2.1.11 on 2019-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('max_device', models.CharField(max_length=50)),
                ('voucher_format', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('purge_after', models.CharField(max_length=50)),
            ],
        ),
    ]
