# Generated by Django 2.2.4 on 2019-08-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
